# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions workflow dependencies (actions/*)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # mods/package.json
  - package-ecosystem: "npm"
    directory: "/mods"
    schedule:
      interval: "weekly"

  # service/package.json
  - package-ecosystem: "npm"
    directory: "/service"
    schedule:
      interval: "weekly"
